### ISSUE TITLE
Mod structure

### ISSUE THREAD

**Issue by Reidond** [SceptreOfficial/Simplex-Support-Services#1]
What do you think about the use of [HEMTT](https://github.com/synixebrett/HEMTT)?

**Comment by SceptreOfficial** [comment]
I don't have any opinion on it. I'm not that advanced. I'm not even following ACE guidelines fully yet.

**Comment by Reidond** [comment]
Don't mind if I do it?

**Comment by SceptreOfficial** [comment]
Nope. Go for it.
