### ISSUE TITLE
Not Compatable with TFAR?

### ISSUE THREAD

**Issue by SavageShark1129** [SceptreOfficial/Simplex-Support-Services#10]
Is there the chance that the mod isn't compatible with the TFAR mod?

**Comment by SceptreOfficial** [comment]
There shouldn't be any reason why... what's your problem? Can you post your .rpt?

**Comment by SavageShark1129** [comment]
=====================================================================
== D:\Games\steamapps\common\Arma 3\Arma3_x64.exe
== "D:\Games\steamapps\common\Arma 3\Arma3_x64.exe" -noSplash -exThreads=7 -enableHT -malloc= -filePatching -noLogs "-mod=D:\Games\steamapps\common\Arma 3\!Workshop\@CBA_A3;D:\Games\steamapps\common\Arma 3\!Workshop\@ace;D:\Games\steamapps\common\Arma 3\!Workshop\@ACE 3 Extension (Animations and Actions);D:\Games\steamapps\common\Arma 3\!Workshop\@ACEX;D:\Games\steamapps\common\Arma 3\!Workshop\@ASR AI3;D:\Games\steamapps\common\Arma 3\!Workshop\@BackpackOnChest;D:\Games\steamapps\common\Arma 3\!Workshop\@Enhanced Movement;D:\Games\steamapps\common\Arma 3\!Workshop\@ZEC - Zeus and Eden Templates - Building Compositions;D:\Games\steamapps\common\Arma 3\!Workshop\@Zeus Enhanced;D:\Games\steamapps\common\Arma 3\!Workshop\@Advanced Sling Loading;D:\Games\steamapps\common\Arma 3\!Workshop\@Advanced Rappelling;D:\Games\steamapps\common\Arma 3\!Workshop\@Achilles;D:\Games\steamapps\common\Arma 3\!Workshop\@WMO - Walkable Moving Objects;D:\Games\steamapps\common\Arma 3\!Workshop\@Simple Single Player Cheat Menu;D:\G
Original output filename: Arma3Retail_DX11_x64
Exe timestamp: 2019/08/03 03:10:02
Current time:  2019/09/14 07:54:17

Type: Public
Build: Stable
Version: 1.94.145977

Allocator: D:\Games\steamapps\common\Arma 3\Dll\tbb4malloc_bi_x64.dll [2017.0.0.0] [2017.0.0.0]
PhysMem: 16 GiB, VirtMem : 131072 GiB, AvailPhys : 6.2 GiB, AvailVirt : 131068 GiB, AvailPage : 6.0 GiB
=====================================================================

 7:54:17 Detected number of DLCs: 22
 7:54:17 DLC index:3 - unable to get DLC data
 7:54:17 ---------------------------------------------------------- Game ----------------------------------------------------------
 7:54:17                                                                name      appId   owned  installed  available   isDlc
 7:54:17                                                              Arma 3     107410     yes        yes        yes      no
 7:54:17                                                             Unknown         -1      no         no         no     yes
 7:54:17 ---------------------------------------------------------- Dlcs ----------------------------------------------------------
 7:54:17  index                                                         name      appId   owned  installed  available   isDlc
 7:54:17      0                              Arma 3 Alpha Lite - expires now     228800      no         no         no     yes
 7:54:17      1                                                Arma 3 Server     233780     yes        yes         no     yes
 7:54:17      2                                                 Arma 3 Tools     233800     yes        yes         no     yes
 7:54:17      4                                            Arma 3 Soundtrack     249860      no         no         no     yes
 7:54:17      5                                                  Arma 3 Maps     249861      no         no         no     yes
 7:54:17      6                                        Arma 3 Tactical Guide     249862      no         no         no     yes
 7:54:17      7                                                  Arma 3 Zeus     275700     yes        yes        yes     yes
 7:54:17      8                                                 Arma 3 Karts     288520     yes        yes        yes     yes
 7:54:17      9                                           Arma 3 Helicopters     304380     yes        yes        yes     yes
 7:54:17     10                                          Arma 3 DLC Bundle 1     304400     yes        yes        yes     yes
 7:54:17     11                                              Arma 3 Marksmen     332350     yes        yes        yes     yes
 7:54:17     12                                               Arma 3 Samples     390500     yes        yes         no     yes
 7:54:17     13                                                  Arma 3 Apex     395180     yes        yes        yes     yes
 7:54:17     14                                           Arma 3 Laws of War     571710     yes        yes        yes     yes
 7:54:17     15                                                  Arma 3 Jets     601670     yes        yes        yes     yes
 7:54:17     16                                          Arma 3 DLC Bundle 2     612480     yes        yes        yes     yes
 7:54:17     17                                                Arma 3 Malden     639600     yes        yes        yes     yes
 7:54:17     18                                  Arma 3 Tac-Ops Mission Pack     744950     yes        yes        yes     yes
 7:54:17     19                                                 Arma 3 Tanks     798390     yes        yes        yes     yes
 7:54:17     20                                               Arma 3 Contact    1021790     yes        yes        yes     yes
 7:54:17     21   Arma 3 Creator DLC: Global Mobilization - Cold War Germany    1042220     yes        yes        yes     yes
 7:54:17 --------------------------------------------------------------------------------------------------------------------------

**Comment by SceptreOfficial** [comment]
Can you post the file itself or a pastebin?

**Comment by SavageShark1129** [comment]
[rpt_file.txt](https://github.com/SceptreOfficial/Simplex-Support-Services/files/3613061/rpt_file.txt)

**Comment by SceptreOfficial** [comment]
That's not a full rpt. Is the game crashing before it loads?

**Comment by SceptreOfficial** [comment]
Also, try loading with only this mod (and requirements) and tfar. You need to rule out the other ones.

**Comment by SavageShark1129** [comment]
Right so, I want to apologize for wasting your time. I forgot to save the mod to my presets when I was switching between them and while in game I saw the support tab for 3den Enhanced and confused it with yours. I works wonderfully with my other mods and its amazing. Once again I apologize for wasting your time. I do have one question, is there a way I can limit it so that only like, the squad leader would be able to request the support?

**Comment by SceptreOfficial** [comment]
No problem. The next update will have a module to assign requesters to different supports. I should have it done within a few days.

I'm closing the issue as it seems to resolved.
