### ISSUE TITLE
Add ejection options for Helocast

### ISSUE THREAD

**Issue by Rex17717** [SceptreOfficial/Simplex-Support-Services#103]
Currently AI cannot be removed from the helicopter even if you order them to disembark while the helo cast action is currently active,

So it would be really useful if we could get the ejection options from paradrop/ unload where you can select who is ejected from the vehicle with the ability to set the ejection interval.

As well as cargo it would be really useful if it could detec anything loaded via VIV for example if you have a boat loaded via VIV into the helicopter, if it could eject the boat first and then infantry jump after just like a real world helocast

**Comment by SceptreOfficial** [comment]
Ejection parameters added with #130
