### ISSUE TITLE
"Drone" like artillery option

### ISSUE THREAD

**Issue by Oriskana** [SceptreOfficial/Simplex-Support-Services#108]
**Is your feature request related to a problem? Please describe.**
Currently when you deselect all Sheaf types for Artillery it will throw an error and won't create the support. 

**Describe the solution you'd like**
For Artillery support to be still created even if all Sheaf types are deselected, under condition that Remote control is enabled. That way it will turn artillery into "Drone" like controlled artillery piece.

**Describe alternatives you've considered**

**Additional context**

**Comment by Oriskana** [comment]
Also an addition: When using Remote control to fire artillery. It has no spread.

**Comment by SceptreOfficial** [comment]
This is now possible with #130. Needs further testing though.
Can you elaborate on the spread issue in a new ticket? I don't understand what you mean.
