### ISSUE TITLE
Danger close warning message 

### ISSUE THREAD

**Issue by Rex17717** [SceptreOfficial/Simplex-Support-Services#109]
I had a very long phase of mod testing as the cas targeting felt very inconsistent, often getting the “no target” notification when trying to call in cas even if the target was in the middle of middle of a open field clear as day for any cas.

it took me far too long to realise that it’s because I was in danger close range without authorising the cas platform to fire danger close.

so I think it would be really useful if instead of getting the normal “target not acquired” message used when it genuinely can’t acquire a target, a different message to the effect of “cas mission aborted, friendly forces are danger close” would avoid any confusion.

**Comment by SceptreOfficial** [comment]
I added basic support for this with #130
More streamlined notifications will be added in the future.
