### ISSUE TITLE
[Feature Request] Disable Automatic Equipping of Parachute

### ISSUE THREAD

**Issue by RichActual** [SceptreOfficial/Simplex-Support-Services#113]
Add CBA setting to transport module to disable automatically equipping ejected units with a parachute. Instead, players will have to equip their own parachute before boarding the transport plain or fall to their deaths and perish.

**Comment by Red-Dog911** [comment]
While you're at it, could you add a way to set the specific class name for the parachute used? Could be useful for a variety of settings, like static chutes for WW2, or even jetpacks for sci-fi settings.

**Comment by SceptreOfficial** [comment]
Settings have been added with #130
