### ISSUE TITLE
it's when you ask the helicopters to turn off their lights and headlights it doesn't work

### ISSUE THREAD

**Issue by djibout60** [SceptreOfficial/Simplex-Support-Services#115]
Hello, very small problem but really small, it's when you ask the helicopters to turn off their lights and headlights it doesn't work, it stays on, in Eden
https://youtu.be/4LmWXWYmHLk

**Comment by SceptreOfficial** [comment]
Should be fixed with https://github.com/SceptreOfficial/Simplex-Support-Services/pull/130
