### ISSUE TITLE
Remote controlling drone does not give you a map

### ISSUE THREAD

**Issue by Lottoungen** [SceptreOfficial/Simplex-Support-Services#117]
**Describe the bug**
When you remote control a drone, it doesnt allow you to view the map while controlling it aka the drone AI does not have a map 

**To Reproduce**
1. Set up a drone CAS loiter support (Greyhawk vanilla drone)
2. Remote control the drone
3. Press M to open map

**Expected behavior**
The ability to see the map

**Comment by SceptreOfficial** [comment]
Setting added with #130 that will automatically add maps to AI inventory.
