### ISSUE TITLE
slingloading doesnt show up when creating it in zeus.

### ISSUE THREAD

**Issue by leifen1** [SceptreOfficial/Simplex-Support-Services#118]
**Describe the bug**
slingloading doesnt show up in the support menu and generates an error when you set it up through zeus.

**To Reproduce**
1. Go into zeus
2. Click on slingloading module
3. complete set up

**Expected behavior**
it should work the same as the supply drop and show up in the support menu.

**Screenshots**
attached screenshots showing off the issue:
![20240729012737_1](https://github.com/user-attachments/assets/9ba15157-1e02-4f59-9d13-bea5a0d1efa5)
![20240729013209_1](https://github.com/user-attachments/assets/d537bef5-2c71-4a3d-b093-3e1fed9739c9)
![20240729013221_1](https://github.com/user-attachments/assets/bf7191e8-6042-4da3-b945-9a68496c6555)
![20240729182452_1](https://github.com/user-attachments/assets/8afc1732-8a15-498b-92b8-a1584c49f0b8)

**Files**
[Arma3_x64_2024-07-29_18-16-44.zip](https://github.com/user-attachments/files/16417239/Arma3_x64_2024-07-29_18-16-44.zip)

**Comment by SceptreOfficial** [comment]
Should be fixed with #130
