### ISSUE TITLE
RHS/Vanilla logistical truck (ammo/repair) non responsive

### ISSUE THREAD

**Issue by DanVonTrap** [SceptreOfficial/Simplex-Support-Services#14]
I synced 3 ammo/repair trucks from RHS to the transport modules (1 per vehicle) then synced to the new "requester assignment" module.

I did the same for x2 ammo repair truck from vanilla arma.

I then went into the game locally and sent them on there way. At first they moved to there first destination. But upon trying to get them to RTB 1 RHS truck would not respond and stayed put. The other returned but collided with the others back at there starting point.

One of the vanilla trucks was knocked on its side and i was prompted with a "new vehicle will respawn in 60 seconds". When the new vehicle spawned 2 of the trucks clos by (1 RHS, 1 vanilla) vanished. No respawn message appeared nothing just gone into thin air.

**Comment by SceptreOfficial** [comment]
I know what you're talking about with the AI being nonresponsive. AI drivers sometimes won't go to their waypoints, and that's vanilla. I'll try to get it more reliable if its possible.
As far as colliding and drivers just being dumb. I can't do anything about that.

When a vehicle respawns, the area around its base position will be cleared. I haven't thought about other supports being in the way of the respawn position. I'll come up with a solution so vehicles aren't blowing each other up or vanishing.
In the mean time, try to space the vehicles apart so they dont cause issues with eachother

**Comment by SceptreOfficial** [comment]
After a lot of testing, there is nothing I can do to jump-start the AI driving. It's a BI issue with the pathing algorithm. It seems to work better if the waypoints are <200m or near a road and if the vehicle isn't nearby any vehicles from where it starts. 

I changed how the obstruction clearing works on respawn, so vehicles shouldn't get deleted anymore: https://github.com/SceptreOfficial/Simplex-Support-Services/commit/2559bd01f0fdfc34a19a7479f01101a100685490
