### ISSUE TITLE
Feature Request - Ability to limit usage based on items

### ISSUE THREAD

**Issue by NZF-JDWang** [SceptreOfficial/Simplex-Support-Services#17]
Could you add a field in the requester module that we can add the classnames of items needed to call supports? That way I can limit support to only people with a long range radio pack for example.

ALiVE does this quite well in that I can add all the long range radio classnames into their module and then anyone who picks up any radio pack can call supports.

**Comment by SceptreOfficial** [comment]
Would this be an "or" option? Like you could assign specific units OR anyone that has said item can use supports synced to the module?

**Comment by NZF-JDWang** [comment]
For my personal use case it would simply be if you don't have the specified items you cannot use the supports. Eg if the team leader with the radio pack goes down you can't call support unless you grab the pack off him.

But if you made it an OR case that would work too as long as I don't have to sync any players.

**Comment by SceptreOfficial** [comment]
So you would require units to be assigned AND have item(s)? Would an addon option suffice for this?

**Comment by NZF-JDWang** [comment]
No for my use case they just need the item, that way anyone can pick up that item and call support.

eg anyone with itemRadio on them can call for supports, but if they drop that item then they're no longer able 

(Hope that makes sense)

**Comment by SceptreOfficial** [comment]
Gotcha, so the OR case. I'll add another setting to select AND/OR.
I'll just make an addon option to list item classnames for now.

**Comment by NZF-JDWang** [comment]
Awesome thank you

**Comment by SceptreOfficial** [comment]
Closing with https://github.com/SceptreOfficial/Simplex-Support-Services/commit/85eb61d5b160f64efa1609565c4df2ccd3ad9d46
