### ISSUE TITLE
Works in editor but not dedicated server.

### ISSUE THREAD

**Issue by Wolf1911** [SceptreOfficial/Simplex-Support-Services#22]
Works when I play the mission in the editor. Does not work when I pbo the file and load it up on dedicated server. It also appears to work on a locally hosted server.

**Comment by SceptreOfficial** [comment]
Can you be more specific

**Comment by Wolf1911** [comment]
> Can you be more specific?

I can see the support menu in hosted or local missions, but not dedicated server ones. Assignment doesn't seem to work in dedicated servers.

**Comment by SceptreOfficial** [comment]
Are you using the new assignment list attribute in the assignment module? I just recently found out synchronizing the players does not work for joining in progress. So I added the list attribute to counteract this

**Comment by Wolf1911** [comment]
Yes, I added the list. Comma separated list.

**Comment by SceptreOfficial** [comment]
It was working fine last I played on my dedi... I'll double check when I have a chance

**Comment by SceptreOfficial** [comment]
Someone else messaged me about the same issue. He said it was related to the special items in the addon options. Apparently leaving it blank isn't working... I'll need to get that fixed. But in the meantime you can try adding a classname everyone would have, like itemMap

**Comment by Wolf1911** [comment]
Oh, alright. Thanks a bunch for the help. I love the mod! I use TFAR for my radio mod, so we tried adding the TFAR radios to the list but to no avail.

**Comment by SceptreOfficial** [comment]
Oh so you were using the list before? What were your settings?

**Comment by SceptreOfficial** [comment]
And just to confirm... you have the settings applied server-side too? If it works in the editor it doesn't make sense why it wouldn't work on the server too since the conditions are evaluated client-side.

**Comment by Wolf1911** [comment]
Yes, in the addon options it is set to override the mission and client settings.

**Comment by SceptreOfficial** [comment]
Ok. When I get a chance I'll test everything to see what's going on

**Comment by SceptreOfficial** [comment]
Just tested on a dedicated server, and I tried every condition - each working as expected. Can you screenshot and attach the settings and how you have the modules set up?

**Comment by Wolf1911** [comment]
![107410_screenshots_20191009163821_1](https://user-images.githubusercontent.com/39203316/66518578-8dc42b80-eab3-11e9-87c8-9ebcfc66ae2d.jpg)
![107410_screenshots_20191009163914_1](https://user-images.githubusercontent.com/39203316/66518579-8dc42b80-eab3-11e9-8680-76a2d089f166.jpg)
![21](https://user-images.githubusercontent.com/39203316/66518722-dda2f280-eab3-11e9-9dcb-d81be2dcc3bd.PNG)
![22](https://user-images.githubusercontent.com/39203316/66518723-dda2f280-eab3-11e9-9f65-6771d2ed6546.PNG)
![23](https://user-images.githubusercontent.com/39203316/66518724-dda2f280-eab3-11e9-9203-bd95afa8f335.PNG)

Individual modules are synced to the heli and to the Assign Requesters module.

**Comment by Wolf1911** [comment]
Weird thing is that it works from Zeus as well on dedi.

**Comment by SceptreOfficial** [comment]
Is it working with itemMap or no?

**Comment by SceptreOfficial** [comment]
Can you add me on Steam so we can PM and figure out the problem quicker?

**Comment by Wolf1911** [comment]
Sure, I'm Wolf on steam. Currently in Arma.

**Comment by SceptreOfficial** [comment]
I'm closing this issue because from our steam conversation, it appears to be a third-party script or addon that is conflicting with this addon.
