### ISSUE TITLE
Issues with Special Items

### ISSUE THREAD

**Issue by NZF-JDWang** [SceptreOfficial/Simplex-Support-Services#29]
Hey I seem to be having all sorts of trouble getting the special items to work properly.

No matter how I set it up the special item doesn't seem to make any difference at all.

The scenario I'm trying to achieve is anyone with the `TFAR_rt1523g_rhs` backpack can call for support. So if the team leader gets shot. anyone can pick up his radio pack and call for support. 

So I've tried having all the player units named in the requester module, then I have `TFAR_rt1523g_rhs` listed as the special item (no quotes) and Special Items Logic set to Assignment AND item. - The result is anyone can call support even without the item.

Then I tried having nothing in the requester module and the logic set to Assignment OR Item - The result is then that no one can call support.

 How can I set it up so anyone with that backpack can call for support?

**Comment by SceptreOfficial** [comment]
Can you try it with a vanilla item, like itemMap? It could be something weird with TFAR's radios. I thought I talked to someone else with a similar issue. But if I'm following you right, you would want OR, this would just give full access to anyone that has that item.

**Comment by TheActionCat** [comment]
I also had issues with this when trying to set up the special item requirement with IFA3 backpack radios. I tested it with the vanilla item, (itemMap) and it worked just fine.

**Comment by SceptreOfficial** [comment]
Actually I realized the problem. It's not actually checking for the backpack itself. Its just checking for all inventory items. Expect an update soon.

**Comment by SceptreOfficial** [comment]
The "Special Items" setting has been converted into the "Access Items" attribute for each individual support module. It should account for TFAR items as well.

Closing with #33
