### ISSUE TITLE
Add permission system

### ISSUE THREAD

**Issue by SceptreOfficial** [SceptreOfficial/Simplex-Support-Services#3]
Need to create some sort of permission system for designating what certain players can request.

**Comment by EpsilonCommunity** [comment]
Check out KP_Ranks for some inspriation: https://github.com/KillahPotatoes/KP-Ranks/blob/master/addons/KP_Ranks/fnc/fn_isAdmin.sqf

**Comment by SceptreOfficial** [comment]
Completed with #13
