### ISSUE TITLE
Issues with Artillery only firing one round...

### ISSUE THREAD

**Issue by EpsilonCommunity** [SceptreOfficial/Simplex-Support-Services#30]
Issues with Artillery only firing one round, even when multiple rounds are selected and default module settings.

**Comment by SceptreOfficial** [comment]
This is a BI issue with the `doArtilleryFire` command. I've tried to alleviate it but I'm pretty sure it's just bugged. I want to figure out how to manually control the gunner and make a custom scripted version, if possible, then this won't be an issue.

**Comment by EpsilonCommunity** [comment]
We've only recently had this issue. So I thought it was something that was changed on your end.

**Comment by SceptreOfficial** [comment]
It's happened to me since I first made the mod. It happens even with zeus, using Achilles or ZEN. I'm going to close this since it is a core BI issue. I'll add an item to the to-do ticket to try and make an alternative in the future.
