### ISSUE TITLE
No suitable signal found

### ISSUE THREAD

**Issue by NZF-JDWang** [SceptreOfficial/Simplex-Support-Services#32]
Been having all sorts of trouble lately with all CAS aircraft reporting "No suitable signal found" whenever I call for a bombing run, they'll then fly over the map location but not drop any ordnance. 

This only seems to happen on the dedicated server, in the editor there's no issue at all.
I've tried both dumb bombs, A-10 gun run, laser guided munitions, all with the same issue.

I am using the USAF mod for aircraft, but not sure why that would make a difference in the editor compared to on the server.

Any ideas what could be wrong?

**Comment by SceptreOfficial** [comment]
I need more info. Map, mods, what request options are used...
I haven't had this issue so I'm not sure what to troubleshoot

**Comment by NZF-JDWang** [comment]
Sorry, on Lythium, using the USAF mod A-10 and F-35's trying gun runs with the A-10, tried dropping mk-82 dumb bombs and GBU-12 LGB's 

I've tried via 10 digit grid, laser marker and even smoke. It all works fine in the editor, but as soon as I upload it to the server I keep getting "No suitable signal found"

**Comment by SceptreOfficial** [comment]
I actually just tested on Lythium with default settings (vanilla A10/options) on our dedi and it worked. I just used a white smoke signal.
It could be the USAF mod. Unless I'm dreaming, but I want to say someone else had an issue with how USAF weapons are configured. Are you using vanilla weapons or USAF's?

**Comment by NZF-JDWang** [comment]
I am using the USAF weapons, but you might have missed the edit I made where I used Zeus and added a pure vanilla A-10, tried a gun run via 10 digit map and got the same message :(

**Comment by SceptreOfficial** [comment]
What about map clicked position instead of grid coords?

**Comment by NZF-JDWang** [comment]
Ok just turned off grid coordinates and tried map click, exactly the same thing :(

**Comment by SceptreOfficial** [comment]
So even when using map position it still says "No suitable signal was found."?

**Comment by NZF-JDWang** [comment]
Correct, I also removed everything from the modules code lines to ensure it wasn't anything in there messing with it, still no change

**Comment by SceptreOfficial** [comment]
I think game logics are being deleted. Are you running antistasi or anything like that? I've run into game logics being deleted before with other people.

**Comment by NZF-JDWang** [comment]
Nope this is an ALiVE mission and we've run this modset all together before (except USAF)
I'll keep digging around and see if I can't narrow things down

**Comment by NZF-JDWang** [comment]
Not sure if you found a bug and fixed it but I haven't been able to replicate the issue on our new mission (which coincided with the update) 

The update is amazing, really like the added features and streamlining.

**Comment by SceptreOfficial** [comment]
Thanks. I'm not sure what might have fixed it or if it was just some weird thing. But either way, I'm going to close this issue.
