### ISSUE TITLE
Need help

### ISSUE THREAD

**Issue by korda1** [SceptreOfficial/Simplex-Support-Services#34]
Hello, on steam you mentioned that if we needed help we could contact you. Precisely I will need help on how to configure so that only one person has access to the simplex mod command? Without other people having access. Your help is welcome. thank you in advance. ( Sorry for my English )

**Comment by SceptreOfficial** [comment]
Put this in the Access Condition field in the support module:
`player getVariable ["canUseSSS",false]`

Then put this in the players init fields that you want to have access:
`this setVariable ["canUseSSS",true,true];`

**Comment by SceptreOfficial** [comment]
Closing this issue since the question was answered. If you have more questions, add me via Steam and we can continue a conversation through chat.
