### ISSUE TITLE
Workaround for broken airports

### ISSUE THREAD

**Issue by klausman** [SceptreOfficial/Simplex-Support-Services#36]
Some maps have (the geometry for) airports, but the runways are not marked as such, resulting in AI not being able to use or see them. While this is a map bug (and ideally would be fixed there), some maps are basically unsupported these days, making fixes very unlikely.

Here's my proposal for a workaround:

In the transport module, allow the specification of the "teleport here" marker, which stands in for the starting location the plane teleports to on an airdrop request.
Add another option to specific a marker that specifies the end of the runway. This way, the plan can teleport, orient itself in the right direction and then do the takeoff.

Alternatively, the second part could be a compass direction to specify, but I fear that may be very fiddly on some runways and with bigger planes.

**Comment by SceptreOfficial** [comment]
Plane AI don't really obey any move commands while they're on the ground. They automatically find the closest runway and take off in the direction it's defined in the map's config.

**Comment by SceptreOfficial** [comment]
da41e7c8267984452dd918a0d421e72641a29008

**Comment by SceptreOfficial** [comment]
Modules now have a "Virtual Runway" attribute to spawn the aircraft **flying** at a certain position. If maps have an incorrect runway configuration, a grounded position may not be useful.
