### ISSUE TITLE
Helicopter Pickup mishaps with AI waypoints 

### ISSUE THREAD

**Issue by KiloRomeo15** [SceptreOfficial/Simplex-Support-Services#37]
Hi, 

Loving the mod so far, by far the best enhancement to Alive and far outclasses the original support system.

One issue I have noticed recently is with Transport Helicopters and the pick up order.

The helicopters land near the smoke/strobe fine, however when I then give my AI squad a "GET IN" order the helicopters do this weird thing where they take off again and land 20m away.

I have tried being in the helicopter first and then ordering "get in" as well and it still presents itself as an issue.

Any ideas ?

THANKS :D

**Comment by SceptreOfficial** [comment]
It's an AI issue. I've tried all I can to stop it from happening, but there isn't any clear explanation on why they do it, nor a consistent way to prevent it.

**Comment by SceptreOfficial** [comment]
da41e7c8267984452dd918a0d421e72641a29008

**Comment by SceptreOfficial** [comment]
Test with the new version and create a new issue if it still occurs.
