### ISSUE TITLE
CAS milsim request off by one error

### ISSUE THREAD

**Issue by warzen** [SceptreOfficial/Simplex-Support-Services#38]
When resquesting CAS in milsim mod (grid), there's an off by one error
Requesting CAS at 030002 gets an acknowlede of a CAS at 029001 and these are the coordinates used by the plane.

**Comment by warzen** [comment]
This is happening when typing a 6 digit coordinate. It's working fine with a 10 digit one.

**Comment by Mysteryjuju** [comment]
It seems to be an issue with the CBA function CBA_fnc_mapGridToPos: [https://github.com/CBATeam/CBA_A3/issues/1362](https://github.com/CBATeam/CBA_A3/issues/1362)

**Comment by warzen** [comment]
CBA function is bugged:
https://cbateam.github.io/CBA_A3/docs/files/common/fnc_mapGridToPos-sqf.html

off by one error in all case
when _dooffset is false, it should return upper left coordinates instead of lower left coordinates (current situation)
anyway, in SSS case, _dooffset should be set to true to aim at the middle of the square instead at one left corner (wether it's top or bottom).

**Comment by Mysteryjuju** [comment]
This issue is partially solved with the new target in center of the square: https://github.com/SceptreOfficial/Simplex-Support-Services/pull/52
Maybe, the next best solution is to wait a fix in CBA.

**Comment by SceptreOfficial** [comment]
https://github.com/CBATeam/CBA_A3/pull/1579
