### ISSUE TITLE
GUI improvement in CAS milsim mod

### ISSUE THREAD

**Issue by warzen** [SceptreOfficial/Simplex-Support-Services#39]
When milsim mod is active, when requesting CAS you have a first GUI to type the grid ref then a second one to select the bearing from the plane while still showing the second option (use the map) that should not be there.
A single interface would be better.

**Comment by warzen** [comment]
in fact, if you select something in the second screen (ex: smoke), you need to reselect map on your next request else it will still wait for a smoke signal (as an example).

**Comment by SceptreOfficial** [comment]
da41e7c8267984452dd918a0d421e72641a29008

**Comment by SceptreOfficial** [comment]
With the new GUI, everything is available in one menu. Marking resolved.
