### ISSUE TITLE
8 digit grid ref in milsim mod ?

### ISSUE THREAD

**Issue by warzen** [SceptreOfficial/Simplex-Support-Services#40]
Is it possible to type an 8 digit grid ref ? and would it have any real effect ?

**Comment by warzen** [comment]
can't reproduce the issue in the last test. may be an error on my side.

do not consider as a bug until further notice.

**Comment by SceptreOfficial** [comment]
It's suppose accept it.

```
CBA_fnc_mapGridToPos:
Converts a 2, 4, 6, 8, or 10 digit grid reference into a Position.
```

I'm closing this issue for now.
