### ISSUE TITLE
Add CAS Plane - Weapon set : empty field could be considered as empty array

### ISSUE THREAD

**Issue by warzen** [SceptreOfficial/Simplex-Support-Services#44]
A tiny improvement:
if the "weapon set" is empty, it could be treated as empty array. Empty field will generate an error in this line:
parseSimpleArray (_logic getVariable ["WeaponSet","[]"]),

**Comment by Mysteryjuju** [comment]
Fixed with: https://github.com/SceptreOfficial/Simplex-Support-Services/pull/53
