### ISSUE TITLE
CAS acknowledge is limited to 6 digit coordinate, even if you type a 10 digit one

### ISSUE THREAD

**Issue by warzen** [SceptreOfficial/Simplex-Support-Services#45]
in milsim mod, if you type a 10 digit coordinate, you still get an acknowledge message using 6 digit coordinate.

**Comment by SceptreOfficial** [comment]
Returning the calculated position back with `mapGridPosition` caps it at 6 digits.

**Comment by SceptreOfficial** [comment]
da41e7c8267984452dd918a0d421e72641a29008
