### ISSUE TITLE
add localization to the mod

### ISSUE THREAD

**Issue by warzen** [SceptreOfficial/Simplex-Support-Services#47]
allow stringtable so that the mod can be translated to other language

**Comment by Mysteryjuju** [comment]
I am working on it ! :)
I will add french translations only.

**Comment by Tanin69** [comment]
Localization in progress ! @SceptreOfficial we're planning to improve consistency also on english strings. But my english is... :cough:. Feel free to correct our corrections :)

**Comment by SceptreOfficial** [comment]
Thanks for all the effort so far

**Comment by Mysteryjuju** [comment]
We are finishing others modules (interaction, module, support). 3 new PR should coming soon.

**Comment by SceptreOfficial** [comment]
Thank you all for your contributions. The rewrite now includes localization support and will need updated translations. I'm marking this resolved. If there are any missing strings or other localization problems, please open a new issue.
