### ISSUE TITLE
Shooting for artillery

### ISSUE THREAD

**Issue by KpoJluK** [SceptreOfficial/Simplex-Support-Services#5]
Is it possible to make a choice to select more than 10 shells in one volley?

**Comment by SceptreOfficial** [comment]
I can increase the slider range. How many do you want?

**Comment by EpsilonCommunity** [comment]
Could you make it so the range is the amount of ammo in the vehicle? 

Might get weird with the aditional vehicles though.

**Comment by SceptreOfficial** [comment]
I increased the slider range to 15 for now. I can add another parameter to the setup function for custom slider ranges. That would open the possibility to limit the amount if admins don't want players calling in excessive artillery.

**Comment by KpoJluK** [comment]
It would be great if you added functionality to the module to limit the number of shots at a time, and if the field is empty then the number is limited by the amount of ammunition in the car

**Comment by SceptreOfficial** [comment]
Completed with #13
