### ISSUE TITLE
Choppers RTB, land, but won't spin down

### ISSUE THREAD

**Issue by foxhound-xdf** [SceptreOfficial/Simplex-Support-Services#51]
Observation is that the choppers don't spin down at RTB generally after a hot exfil, ie the door gunners have fired.

**Comment by CommandoCat** [comment]
Helicopters do spin down for me, using RHS helicopters.

**Comment by SceptreOfficial** [comment]
da41e7c8267984452dd918a0d421e72641a29008

**Comment by SceptreOfficial** [comment]
Test with the new version and create a new issue if it still occurs.
