### ISSUE TITLE
VTOL Gunship Extension [Fire X on Smoke]

### ISSUE THREAD

**Issue by EpsilonCommunity** [SceptreOfficial/Simplex-Support-Services#6]
Having the VTOL loiter and then to Fire on Smoke. Just like the other CAS.

**Comment by SceptreOfficial** [comment]
I'll see what I can do.

**Comment by EpsilonCommunity** [comment]
Awesome

**Comment by EpsilonCommunity** [comment]
Any update?

**Comment by SceptreOfficial** [comment]
No, sorry.

**Comment by EpsilonCommunity** [comment]
Any update?

**Comment by SceptreOfficial** [comment]
I haven't had a chance to work on this feature yet. I will be doing some work on the drone functionality for the next update, and I'll try to get something like this working for both if I have time.

**Comment by EpsilonCommunity** [comment]
Awesome, keep up the good work! :)

**Comment by SceptreOfficial** [comment]
da41e7c8267984452dd918a0d421e72641a29008

**Comment by SceptreOfficial** [comment]
Targeting feature added in the new version
