### ISSUE TITLE
Duplicate Entries via Zeus (CAS Gunship & Logistics Station)

### ISSUE THREAD

**Issue by Sora012** [SceptreOfficial/Simplex-Support-Services#68]
As the title says, when playing as zeus and placing a "CAS Gunship" module, you get the value from the filled in prompt, and a secondary "Blackfish" option. This also applies to the Logistics Station as well.

**Comment by SceptreOfficial** [comment]
Can you post a screenshot?

**Comment by Sora012** [comment]
![Image of Duplicate Gunship](https://steamuserimages-a.akamaihd.net/ugc/1620691371164390533/62C2584EB75A02202DCB4F38EDA13578319A3595/)

The same thing happens with logistic stations.

**Comment by SceptreOfficial** [comment]
I can't replicate the issue on my end. What additional mods are you running?

**Comment by Sora012** [comment]
My mod list is:
AWESome : Aerial Warfare Enhanced Somehow
CBA_A3
JSRS SOUNDMOD
Simplex Support Services
ZEC - Zeus and Eden Templates / Building Compositions
Zeus Enhanced
Zeus Enhanced - ACE3 Compatibility
ace
dzn Artillery Illumination

**Comment by Sora012** [comment]
Are you testing against a dedicated server? My self hosted game doesn't have the issue with the mods, but as soon as I join my dedicated server, and use either logistics or gunship, it gives duplicate entries.

I'm in the proccess of disabling Zeus enhanced serverside and client side to see if its the issue.

**Comment by SceptreOfficial** [comment]
I did test in MP. I'm not sure where "added by prompt" is even coming from. Does the mission have some sort of extra feature that interfaces with this mod?

**Comment by Sora012** [comment]
Here is a [youtube video](https://www.youtube.com/watch?v=H4qpenxrb8M) showing the process I am using.

No the mission doesn't interact with the mod at all.

**Comment by SceptreOfficial** [comment]
Can you run a test with only the required mods on an empty Zeus mission?

**Comment by Sora012** [comment]
Running just ACE, CBA_A3, SSS. (Server & Client)
Uploaded a fresh vanilla mission. (No scripts, simple SQM with a single blufor soldier and zeus curator attached without forced interface)

[youtube video](https://www.youtube.com/watch?v=8LQp8RqvyoM)

**Comment by Mysteryjuju** [comment]
Reproduced too on my server with latest develop branch.
Interesting thing: when you add a module with Zeus, but you cancel the request, the support is still added. It must not.

**Comment by SceptreOfficial** [comment]
Is the cancel thing happening for all supports or just these 2?

**Comment by Mysteryjuju** [comment]
Only these two during my tests but I didn't test all SSS possibilities. No particular errors in RPT files (on server and client).

**Comment by SceptreOfficial** [comment]
My suspicion is that maybe the module/logic's locality is on the server and the client, somehow. So it's running the module init script on both machines. It doesn't make sense with how zeus is suppose to work. And I don't get why the initial issue was showing "Added by prompt." 
Unless something changed with arma, cba, or ace recently and it's updating logic locality automatically, this shouldn't be happening. Either way, this should be solved by checking `if (!local _logic)` at the start of each module function instead of later on. I'll go through and update the module functions @Mysteryjuju

**Comment by Sora012** [comment]
Curious why this was closed? This is still a valid bug, atleast in released versions. Has develop fixed it?

**Comment by SceptreOfficial** [comment]
It will be resolved in the next version. Sorry for clarification.

**Comment by Sora012** [comment]
This is still an active issue. Is the project still being worked on?

**Comment by SceptreOfficial** [comment]
Yes
