### ISSUE TITLE
Add maritime transport

### ISSUE THREAD

**Issue by DarkLab-s** [SceptreOfficial/Simplex-Support-Services#7]
Adding the ability to call for maritime.

**Comment by kalle1556** [comment]
Add ability to decide altitude for planes to Very Low.

Den mån 2 sep. 2019 kl 13:10 skrev Dare H. <notifications@github.com>:

**Comment by SceptreOfficial** [comment]
I'd like to expand to more services beyond just helicopter transport. If you have any more ideas on this or specific functions that would make it better, let me know.

@kalle1556
Please open another issue so stuff isn't off topic, and if you can elaborate on what exactly you're wanting. Im not sure if you mean the CAS plane approach angle/height or not.

**Comment by DarkLab-s** [comment]
@spectreOfficial 

Of course. 

Maritime Transportation Module that is synced to AI Boat just like helicopter module.
Drop AI boat in with editor, link with Maritime Transportation Module.

   >Pick Up - (Shore) Search for smoke or IR strobe (if possible). Boat would possibly have to wait a 
                      few meters off shore so that the AI does not beach itself
                   - (Water) Search for smoke or IR strobe (if possible). 

   >Move    - Move to Map Marker (Like Helicopter Transport)

   >Move(Engine off)     - Move to Map Marker (Like Helicopter Transport). Shut off engine once 
                                         location is reached. 

   >Loiter     - Loiter in area (with radius slider). This can be used to provide fire support within an area 
                      or make sure the boat isn't a sitting target.

   >Change Behavior

 **>Load/Unload Cargo     - I know you have plans to build in supply function. Consider adding it to boats. We often use the Mk. V SOC boat to hold a small assault boat in cargo. Having he ability to unload it while sitting in the passengers seat and load it into cargo when driving up to the rear of the MK. V SOC would be nice but I understand if it isn't in the scope of your project. I know ACE already has these function but being able to access through your ACE interface would be very nice.

There would move likely have to be a check for distance to land to prevent AI from beaching and to disallow marker placement on land.

If you would like me to elaborate any further I am more than happy. You are doing great work.

**Comment by SceptreOfficial** [comment]
Great ideas. Yeah, with enough patience, almost anything can be tuned right with the AI. Your loiter with a radius slider idea is a good idea for other stuff too. 
I'm not sure of loading/unloading cargo would be within scope or not. It really depends on the interface I guess. To me that sounds like a job for a player, but if a simple/smooth enough routine is figured out I'm sure I could fit into the mod.

**Comment by SceptreOfficial** [comment]
Primary functionality implemented with #13
