### ISSUE TITLE
2 Items as requirement for access

### ISSUE THREAD

**Issue by xMetro** [SceptreOfficial/Simplex-Support-Services#71]
Is there a way so i can make 2 item as a requirement?

I want to make to roles Forward Observer and JTAC
And they both use the ACRE_PRC117F plus a ekstra item that seprate the 2 roles

**Comment by SceptreOfficial** [comment]
It just checks for any of the items listed. If you need more specialized restrictions, use the access condition for more customization. What are the extra items that separate the 2 roles?

**Comment by xMetro** [comment]
My plan was 
ACRE_PRC117F & ACE_artilleryTable = Artillery
ACRE_PRC117F & ACE_SpottingScope = CAS

I already limited so its only 2 specific units that can use SSS with access condition.
Is there a way to seperate them even more?

**Comment by SceptreOfficial** [comment]
The access condition is the best way to control access since it's just code that runs every time the menu is opened. I would just use the artillery table and spotting scope as the access items, then

**Comment by SceptreOfficial** [comment]
The access condition is the best way to control access. I would just use the artillery table and spotting scope as the items, then check for the acre radio in the players inventory via access condition, plus whatever else you want to use to prevent others from accessing the supports. Or just forget the access item option entirely and check for everything in the condition, which is what I would do.

**Comment by xMetro** [comment]
Yeah, that was my thought aswell.
ill figure something out, im just not the best at script stuff, so if you could point me in a direction that would be a big help

**Comment by SceptreOfficial** [comment]
What do you currently have in your access condition?

**Comment by xMetro** [comment]
This "player getVariable ["canUseSSS",false]" and the the player init aswell

**Comment by SceptreOfficial** [comment]
Actually thinking about it more, just use the acre radio in the access items, then use this code in the condition:

`player getVariable ["canUseSSS",false] && "ace_spottingscope" in _targetItems`

`_targetItems` is an array of all the inventory items on the player that can be accessed in this scope. The class name  of the spotting scope/artillery table need to be lower case.

**Comment by xMetro** [comment]
Thanks, im gonna test it out!

**Comment by xMetro** [comment]
Wuhu that worked! thanks for the help!
