### ISSUE TITLE
CAS Planes will fire salvos of ATGMs as if they were rockets

### ISSUE THREAD

**Issue by jimshacklock** [SceptreOfficial/Simplex-Support-Services#72]
If a CAS plane is assigned an ATGM type missile, such as a Vanilla Macer, when called in the plane fires a full salvo of these as if they were rocket pods, instead of a single missile. This occurred with the following ammo class: Missile_AGM_02_Plane_CAS_01_F

I think this may be related to the way vanilla CAS modules work, as this sounds familiar from those. Is it possible to set the weapons to be treated like a bomb in some way (drops/fires a single one) or something to that effect?

**Comment by SceptreOfficial** [comment]
You are correct. You can't change the amount, but more customization for the CAS support will be available in the future.
