### ISSUE TITLE
Helicopters

### ISSUE THREAD

**Issue by PimpDaddyLucky** [SceptreOfficial/Simplex-Support-Services#75]
Ai helicopters are all messed up with certain AI mods such as VCOM and LAMBS. The helicopters only seem to take off when ordered after all players have exited vehicle. Helicopters also will just circle LZ and never land or will take off just to hover in place. This issue is with all helicopters. Especially Helicopters that are added in from RHS. Both transport and CAS. The reason why I think the mods that make AI smarter are to blame is because I've used SSS for years with minimal issues, until i started looking into mods to make AI more challenging.

**Comment by NZF-JDWang** [comment]
Works fine with LAMBs we use it all the time, and really it's not an issue with Simplex but instead with VCOM because that's what's actively taking over your supports.
Better off raising an issue with the VCOM dev

**Comment by Repolak** [comment]
We are actually not running VCOM at all, only Lambs and TCL and are having this issue.

**Comment by DanVonTrap85** [comment]
Is this still an issue?
