### ISSUE TITLE
When using a headless...

### ISSUE THREAD

**Issue by Eagle-Studios** [SceptreOfficial/Simplex-Support-Services#77]
When using our headless client, virtual simplex supports (ex CAS) will ALWAYS report no valid/suitable signal. 

I presume this is to do with them getting transferred to the headless and losing their tasking.

**Comment by SceptreOfficial** [comment]
da41e7c8267984452dd918a0d421e72641a29008

**Comment by SceptreOfficial** [comment]
Test with the new version and create a new issue if it still occurs.
