### ISSUE TITLE
useing IFA3

### ISSUE THREAD

**Issue by DK-Rex** [SceptreOfficial/Simplex-Support-Services#78]
Hey
We play with the mod IFA3 and use planes from here, for that we use Simplex Support Services.
But when we have to use CAS, they always hit several 100 meters to the side, anyone know what the problem could be?

They never hit their mark or just miss, always 100 meters to the side

Anyone know what the problem might be?

**Comment by SceptreOfficial** [comment]
da41e7c8267984452dd918a0d421e72641a29008

**Comment by SceptreOfficial** [comment]
Test with the new version and create a new issue if it still occurs.
