### ISSUE TITLE
Add land vehicle support

### ISSUE THREAD

**Issue by OfficialNoms** [SceptreOfficial/Simplex-Support-Services#8]
Adding land vehicle support would be an excellent step forward in supporting smaller milsim groups and casual communities who want missions that are easy to play with support so that they don't get overwhelmed during missions. 

**Vehicle Transport Module**
Sync this module to any ground vehicle with passenger seats. Options:
> Pick Up - AI drives to a selected location on the map and waits. Optionally you could add so that it looks for a smoke or strobe so it can go to a more precise location after confirming.
> Move - AI drives to a selected location on the map
> Move ( Engine Off) - AI drives to selected location, turns the engine off on arrival.
> Patrol - AI drives to the selected location, then drives around, patrolling the immediate area within a specificed area. Should include a "radius" slider to specify the patrol distance.

**Vehicle Support Module**
Sync this module to any ground vehicle with weapon turrets.
> Patrol - AI drives to the selected location, and then drives around, patrolling the immediate area. Should include a "radius" slider to specify the patrol distance.
> Sentry - AI drives to the selected location and waits, attacking and killing any enemies it encounters.
> Search and Destroy - AI drives to the selected location, looks for any enemy in the area, engages them. 
> Support Player - AI drives to within [x] distance of a specified player, and remains within that distance as the player moves. 

It could be expanded in the future with cargo supply modules that could look for specific compatible ACE loadable crates in the base area, loading them via ACE cargo, driving to a location, and then ACE unloading them.

**Comment by OfficialNoms** [comment]
After a bit of testing (I was planning on seeing if I could make the necessary changes and do a pull request) I discovered that due to the way you wrote the transport functions, it works on ground vehicles for transport already, as there's no checks to see if the vehicle is an air vehicle or not.

With some basic checks for the vehicle type, you could probably get away with a single "Add Transport Vehicle" option and have the ACE options do a few checks, so it doesn't show options like flying height and fast-roping.

**Comment by SceptreOfficial** [comment]
Yeah, I'm going to restructure some stuff before the next update, so hold off on a PR for now. I'll probably categorize things differently since a support vehicle wouldn't fit as CAS or transport. If you have any other suggestions, let me know

**Comment by SceptreOfficial** [comment]
Primary functionality implemented with #13
