### ISSUE TITLE
Mods initialization issue

### ISSUE THREAD

**Issue by LeonFAM** [SceptreOfficial/Simplex-Support-Services#80]
Hello, I have a concern, the words do not initialize during the launch of the mission, all the supports are absens during the launch of the game, I am obliged to put the modules directly in Zeus

**Comment by siKruger** [comment]
Got the same issue +1

**Comment by Battle8111** [comment]
I also have the same issue as of 4/12/2023 - I wonder if its related to ALIVE maybe deleting the modules? I am only guessing with no proof to back that up.

**Comment by SceptreOfficial** [comment]
da41e7c8267984452dd918a0d421e72641a29008

**Comment by SceptreOfficial** [comment]
Test with the new version and create a new issue if it still occurs.
