### ISSUE TITLE
Feature Request: Clear Area/Despawn

### ISSUE THREAD

**Issue by rco-titus** [SceptreOfficial/Simplex-Support-Services#81]
Add an option to logistic stations to delete vehicles/objects near the module.

This idea came to me when using SSS on a multiplayer server and my friends were wanting me to delete vehicles at the logistics station as they were spawning the wrong one or spawned too many vehicles so I guess this could be more of a quality of life thing.

This would help as players who do not have access to zues can despawn vehicles at the station or objects if they or someone else spawned too many or abused the station by continuously spawning multiple vehicles.

**Comment by SceptreOfficial** [comment]
Added.
https://github.com/SceptreOfficial/Simplex-Support-Services/commit/9d618dfff16fa12b0c4c184098dacde7bbef3d1a
https://github.com/SceptreOfficial/Simplex-Support-Services/commit/b68f437ba7ec7c09511e2ecbb0cfd8a223488c2f
