### ISSUE TITLE
How to get a custom plane loadout easier than digging through config viewer

### ISSUE THREAD

**Issue by DREBIN692** [SceptreOfficial/Simplex-Support-Services#82]
I remember there being an easier way to get the plane loadouts for CAS Plane
It entailed naming the plane myplane in the editor, starting it in SP and then using the admin menu to type
something myplane and it shows the plane's loadout in the admin menu, which can then be copy pasted into the
CAS plane module.
Can you put that in the wiki, on how to do this specific task

**Comment by SceptreOfficial** [comment]
`weapons myPlane`

**Comment by DREBIN692** [comment]
thanks

**Comment by SceptreOfficial** [comment]
da41e7c8267984452dd918a0d421e72641a29008
