### ISSUE TITLE
Artillery Module does not recognise 60mm mortars

### ISSUE THREAD

**Issue by Isaac-Chadirchi** [SceptreOfficial/Simplex-Support-Services#84]
The artillery module does not recognise 60mm mortars from either the 3CB mods, the M224 mod, or the vz99 60mm Mortar mod. Mod is functioning correctly with 81mm mortars.

**Comment by SceptreOfficial** [comment]
da41e7c8267984452dd918a0d421e72641a29008

**Comment by SceptreOfficial** [comment]
Test with the new version and create a new issue if it still occurs.
