### ISSUE TITLE
Land transport sometimes try to kill every AI instead of RTB

### ISSUE THREAD

**Issue by igorpc1** [SceptreOfficial/Simplex-Support-Services#87]
SSS ver: 0.3.2.2
When land transport with gun ordered to RTB sometimes AI decide to kill enemy instead of RTB'ing.
Expected behaviour: Land transport driver ignore AI and just move to base, Gunner still provide covering fire

**Comment by SceptreOfficial** [comment]
da41e7c8267984452dd918a0d421e72641a29008

**Comment by SceptreOfficial** [comment]
Test with the new version and create a new issue if it still occurs.
