### ISSUE TITLE
change pylons of the CAS Plane

### ISSUE THREAD

**Issue by cruiser1092** [SceptreOfficial/Simplex-Support-Services#88]
Hello, first of all I would like to congratulate you on the magnificent mod you created. Even though it is dated, my group and I still use it after years and we are grateful to you.

I have a question: if I wanted to change pylons to the CAS module and insert particular pylons of a personal aircraft (mod F-117 with 3x GBU12) how could I do it?
Furthermore, I wanted to ask you if it would be possible to possibly create the possibility of carrying out a carpet bombing

**Comment by SceptreOfficial** [comment]
Use the 'weapon set' module attribute. It's an array of weapon classes or weapon-magazine pairs/arrays. For example:
`["weapon_class_alpha","weapon_class_bravo"]` 
or 
`["standalone_weapon",["paired_weapon","paired_magazine"]]`

**Comment by cruiser1092** [comment]
Thanks so much for the quick response!
I also wanted to ask you if there is the possibility of creating a carpet bombing

**Comment by cruiser1092** [comment]
> Utilizza l'attributo del modulo 'set di armi'. Si tratta di una serie di classi di armi o coppie/array di caricatori di armi. Ad esempio: `["weapon_class_alpha","weapon_class_bravo"]` o `["standalone_weapon",["paired_weapon","paired_magazine"]]`

but would "alpha" stand for the name of the aircraft variable?

**Comment by SceptreOfficial** [comment]
You're welcome. If you have more questions, I'm more active on discord if you want to join the server: https://discord.gg/zNPxjHvb8X

Carpet bombing is a highly requested feature that is coming. I've been rewriting the entire mod and CAS is the last service I need to finish up. I'm hoping to have it done by the end of the year.

Those examples don't refer to any existing weapon class or need to reference a variable. I just wrote it as a placeholder for whatever weapon classes you want to use.

**Comment by SceptreOfficial** [comment]
Here is a list of the vanilla weapon classes you can reference. Other mods may have a website. But if not, you can view them in-game via the config viewer.
https://community.bistudio.com/wiki/Arma_3:_CfgWeapons_Vehicle_Weapons
