### ISSUE TITLE
Can you add the Variables that you mentioned in the Steam Workshop onto Github

### ISSUE THREAD

**Issue by EpsilonCommunity** [SceptreOfficial/Simplex-Support-Services#9]
Can you add the Variables that you mentioned in the Steam Workshop onto Github

**Comment by SceptreOfficial** [comment]
The enabling variables?

**Comment by SceptreOfficial** [comment]
https://github.com/SceptreOfficial/Simplex-Support-Services/blob/master/addons/main/XEH_preInit.sqf#L119-L129

Current variable names:

- SSS_showArtillery
- SSS_showCAS
- SSS_showTransport
- SSS_showCASDrones
- SSS_showCASGunships
- SSS_showCASHelicopters
- SSS_showCASPlanes
- SSS_showGroundSupportVehicles
- SSS_showTransportHelicopters
- SSS_showTransportLandVehicles
- SSS_showTransportMaritime
