### ISSUE TITLE
SSS creates unplayable mpmission

### ISSUE THREAD

**Issue by Honorbreeze** [SceptreOfficial/Simplex-Support-Services#91]
Anytime I place a Simplex Support Services system I receive an error and am then unable to load the mission on my arma 3 server.  The error is No entry "bin\config.bin/CfgPatches/Hyun_XP.units'. I have looked in all of my mods .pbo's and even the .pbo for simplex services and have nothing to do with a Hyun_XP. If anyone has an suggestions I will gladly listen
!
![20240106123354_1](https://github.com/SceptreOfficial/Simplex-Support-Services/assets/30018813/925cf617-7759-4a45-ad34-aafbb8d5f700)

**Comment by SceptreOfficial** [comment]
That error is not related to SSS. You're probably not loading a mod on your server or client and there's a mismatch.

**Comment by SceptreOfficial** [comment]
@Honorbreeze You'll need to test this without other mods loaded. Make a new issue if the problem still occurs, and send an RPT if so. I'm closing this issue for now.
